ifndef S
S:=$(shell cd ../../../..; pwd)
endif
TARGET= ${S}/Targets/LS232_sm502
SUBTARGET?=ls232
CPPFLAGS=-mips2 -mfp32

%OBJS

%CFILES

%SFILES

%LOAD

export CFILES OBJS SFILES
include ${S}/Makefile.inc

%RULES
