ifndef S
S:=$(shell cd ../../../..; pwd)
endif
TARGET= ${S}/Targets/Bonito2g5ddr2_1a
SUBTARGET?=Bonito
CPPFLAGS=-mips3 -mfp32

%OBJS

%CFILES

%SFILES

%LOAD

export CFILES OBJS SFILES
include ${S}/Makefile.inc

%RULES
