libata-scsi.o: drivers/scsi/libata-scsi.c ./include/linux/autoconf.h \
  include/linux/kernel.h \
  /mnt/sdb2/opt/gcc-3.4.6-2f/bin/../lib/gcc/mipsel-linux/3.4.6/include/stdarg.h \
  include/linux/linkage.h include/asm/linkage.h include/linux/stddef.h \
  include/linux/compiler.h include/linux/compiler-gcc3.h \
  include/linux/compiler-gcc.h include/linux/types.h \
  include/linux/posix_types.h include/asm/posix_types.h \
  include/asm/sgidefs.h include/asm/types.h include/linux/bitops.h \
  include/asm/bitops.h include/asm/bug.h include/asm/break.h \
  include/asm-generic/bug.h include/asm/byteorder.h \
  include/linux/byteorder/little_endian.h include/linux/byteorder/swab.h \
  include/linux/byteorder/generic.h include/asm/cpu-features.h \
  include/asm/cpu.h include/asm/cpu-info.h include/asm/cache.h \
  include/asm-mips/mach-generic/kmalloc.h \
  include/asm-mips/mach-generic/cpu-feature-overrides.h \
  include/linux/irqflags.h include/asm/irqflags.h include/asm/hazards.h \
  include/asm/war.h include/asm-generic/bitops/non-atomic.h \
  include/asm-generic/bitops/__ffs.h include/asm-generic/bitops/ffs.h \
  include/asm-generic/bitops/fls.h include/asm-generic/bitops/fls64.h \
  include/asm-generic/bitops/ffz.h include/asm-generic/bitops/find.h \
  include/asm-generic/bitops/sched.h include/asm-generic/bitops/hweight.h \
  include/asm-generic/bitops/ext2-non-atomic.h \
  include/asm-generic/bitops/le.h \
  include/asm-generic/bitops/ext2-atomic.h \
  include/asm-generic/bitops/minix.h include/linux/blkdev.h \
  include/linux/major.h include/linux/genhd.h include/linux/device.h \
  include/linux/ioport.h include/linux/kobject.h include/linux/list.h \
  include/linux/poison.h include/linux/prefetch.h include/asm/processor.h \
  include/linux/cpumask.h include/linux/threads.h include/linux/bitmap.h \
  include/linux/string.h include/asm/string.h include/asm/cachectl.h \
  include/asm/mipsregs.h include/asm/prefetch.h include/asm/system.h \
  include/asm/addrspace.h include/asm-mips/mach-generic/spaces.h \
  include/asm/dsp.h include/asm/ptrace.h include/asm/isadep.h \
  include/linux/sysfs.h include/asm/atomic.h include/linux/spinlock.h \
  include/linux/preempt.h include/linux/thread_info.h \
  include/asm/thread_info.h include/linux/stringify.h \
  include/linux/spinlock_types.h include/linux/lockdep.h \
  include/linux/debug_locks.h include/linux/stacktrace.h \
  include/linux/spinlock_types_up.h include/linux/spinlock_up.h \
  include/linux/spinlock_api_up.h include/asm-generic/atomic.h \
  include/linux/rwsem.h include/linux/rwsem-spinlock.h \
  include/linux/kref.h include/linux/wait.h include/asm/current.h \
  include/linux/klist.h include/linux/completion.h include/linux/module.h \
  include/linux/sched.h include/linux/auxvec.h include/asm/auxvec.h \
  include/asm/param.h include/linux/capability.h include/linux/timex.h \
  include/linux/time.h include/linux/seqlock.h include/asm/timex.h \
  include/asm-mips/mach-generic/timex.h include/linux/jiffies.h \
  include/linux/calc64.h include/asm/div64.h include/linux/rbtree.h \
  include/linux/errno.h include/asm/errno.h \
  include/asm-generic/errno-base.h include/linux/nodemask.h \
  include/linux/numa.h include/asm/semaphore.h include/asm/page.h \
  include/asm-generic/memory_model.h include/asm-generic/page.h \
  include/asm/mmu.h include/asm/cputime.h include/asm-generic/cputime.h \
  include/linux/smp.h include/linux/sem.h include/linux/ipc.h \
  include/asm/ipcbuf.h include/asm/sembuf.h include/linux/signal.h \
  include/asm/signal.h include/asm/sigcontext.h include/asm/siginfo.h \
  include/asm-generic/siginfo.h include/linux/securebits.h \
  include/linux/fs_struct.h include/linux/pid.h include/linux/rcupdate.h \
  include/linux/cache.h include/linux/percpu.h include/linux/slab.h \
  include/linux/gfp.h include/linux/mmzone.h include/linux/init.h \
  include/linux/memory_hotplug.h include/linux/notifier.h \
  include/linux/mutex.h include/linux/topology.h include/asm/topology.h \
  include/asm-mips/mach-generic/topology.h include/asm-generic/topology.h \
  include/linux/kmalloc_sizes.h include/asm/percpu.h \
  include/asm-generic/percpu.h include/linux/seccomp.h \
  include/linux/futex.h include/linux/rtmutex.h include/linux/plist.h \
  include/linux/param.h include/linux/resource.h include/asm/resource.h \
  include/asm-generic/resource.h include/linux/timer.h \
  include/linux/hrtimer.h include/linux/ktime.h include/linux/aio.h \
  include/linux/workqueue.h include/linux/aio_abi.h \
  include/linux/sysdev.h include/linux/pm.h include/linux/stat.h \
  include/asm/stat.h include/linux/kmod.h include/linux/elf.h \
  include/linux/elf-em.h include/asm/elf.h include/linux/moduleparam.h \
  include/asm/local.h include/asm/module.h include/asm/uaccess.h \
  include/asm-generic/uaccess.h include/linux/fs.h include/linux/limits.h \
  include/linux/ioctl.h include/asm/ioctl.h include/linux/kdev_t.h \
  include/linux/dcache.h include/linux/radix-tree.h \
  include/linux/prio_tree.h include/linux/quota.h \
  include/linux/dqblk_xfs.h include/linux/dqblk_v1.h \
  include/linux/dqblk_v2.h include/linux/nfs_fs_i.h include/linux/nfs.h \
  include/linux/sunrpc/msg_prot.h include/linux/fcntl.h \
  include/asm/fcntl.h include/asm-generic/fcntl.h include/linux/err.h \
  include/linux/pagemap.h include/linux/mm.h include/asm/pgtable.h \
  include/asm/pgtable-64.h include/asm-generic/pgtable-nopud.h \
  include/asm/io.h include/asm/pgtable-bits.h \
  include/asm-mips/mach-generic/ioremap.h \
  include/asm-mips/mach-generic/mangle-port.h \
  include/asm-generic/pgtable.h include/linux/page-flags.h \
  include/linux/vmstat.h include/linux/config.h include/linux/autoconf.h \
  include/linux/highmem.h include/asm/cacheflush.h \
  include/linux/backing-dev.h include/linux/mempool.h include/linux/bio.h \
  include/linux/ioprio.h include/asm/scatterlist.h \
  include/linux/elevator.h include/scsi/scsi.h include/scsi/scsi_host.h \
  include/scsi/scsi_cmnd.h include/linux/dma-mapping.h \
  include/asm/dma-mapping.h include/scsi/scsi_eh.h \
  include/scsi/scsi_device.h include/scsi/scsi_tcq.h \
  include/scsi/scsi_transport.h include/linux/transport_class.h \
  include/linux/attribute_container.h include/linux/libata.h \
  include/linux/delay.h include/asm/delay.h include/asm/compiler.h \
  include/linux/interrupt.h include/linux/irqreturn.h \
  include/linux/hardirq.h include/linux/smp_lock.h include/asm/hardirq.h \
  include/linux/irq.h include/asm/irq.h include/asm/mipsmtregs.h \
  include/asm-mips/mach-generic/irq.h include/asm/hw_irq.h \
  include/linux/profile.h include/linux/irq_cpustat.h include/linux/pci.h \
  include/linux/pci_regs.h include/linux/pci_ids.h \
  include/linux/mod_devicetable.h include/linux/dmapool.h \
  include/asm/pci.h include/asm-generic/pci-dma-compat.h \
  include/linux/ata.h include/linux/hdreg.h drivers/scsi/libata.h
drivers/scsi/libata-scsi.o:
	  mipsel-linux-gcc -Wp,-MD,drivers/scsi/.libata-scsi.o.d  -nostdinc -isystem /mnt/sdb2/opt/gcc-3.4.6-2f/bin/../lib/gcc/mipsel-linux/3.4.6/include -D__KERNEL__ -Iinclude  -include include/linux/autoconf.h -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -O2  -mabi=64 -G 0 -mno-abicalls -fno-pic -pipe -msoft-float -ffreestanding  -march=r4600 -Wa,--trap -Iinclude/asm-mips/mach-longmeng -Wa,-mfix-gs2f-kernel -Iinclude/asm-mips/mach-generic -fomit-frame-pointer  -Wdeclaration-after-statement      -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(libata_scsi)"  -D"KBUILD_MODNAME=KBUILD_STR(libata_scsi)" -c -o drivers/scsi/libata-scsi.o drivers/scsi/libata-scsi.c
libata-core.o: drivers/scsi/libata-core.c ./include/linux/autoconf.h \
  include/linux/kernel.h \
  /mnt/sdb2/opt/gcc-3.4.6-2f/bin/../lib/gcc/mipsel-linux/3.4.6/include/stdarg.h \
  include/linux/linkage.h include/asm/linkage.h include/linux/stddef.h \
  include/linux/compiler.h include/linux/compiler-gcc3.h \
  include/linux/compiler-gcc.h include/linux/types.h \
  include/linux/posix_types.h include/asm/posix_types.h \
  include/asm/sgidefs.h include/asm/types.h include/linux/bitops.h \
  include/asm/bitops.h include/asm/bug.h include/asm/break.h \
  include/asm-generic/bug.h include/asm/byteorder.h \
  include/linux/byteorder/little_endian.h include/linux/byteorder/swab.h \
  include/linux/byteorder/generic.h include/asm/cpu-features.h \
  include/asm/cpu.h include/asm/cpu-info.h include/asm/cache.h \
  include/asm-mips/mach-generic/kmalloc.h \
  include/asm-mips/mach-generic/cpu-feature-overrides.h \
  include/linux/irqflags.h include/asm/irqflags.h include/asm/hazards.h \
  include/asm/war.h include/asm-generic/bitops/non-atomic.h \
  include/asm-generic/bitops/__ffs.h include/asm-generic/bitops/ffs.h \
  include/asm-generic/bitops/fls.h include/asm-generic/bitops/fls64.h \
  include/asm-generic/bitops/ffz.h include/asm-generic/bitops/find.h \
  include/asm-generic/bitops/sched.h include/asm-generic/bitops/hweight.h \
  include/asm-generic/bitops/ext2-non-atomic.h \
  include/asm-generic/bitops/le.h \
  include/asm-generic/bitops/ext2-atomic.h \
  include/asm-generic/bitops/minix.h include/linux/module.h \
  include/linux/sched.h include/linux/auxvec.h include/asm/auxvec.h \
  include/asm/param.h include/linux/capability.h include/linux/spinlock.h \
  include/linux/preempt.h include/linux/thread_info.h \
  include/asm/thread_info.h include/asm/processor.h \
  include/linux/cpumask.h include/linux/threads.h include/linux/bitmap.h \
  include/linux/string.h include/asm/string.h include/asm/cachectl.h \
  include/asm/mipsregs.h include/asm/prefetch.h include/asm/system.h \
  include/asm/addrspace.h include/asm-mips/mach-generic/spaces.h \
  include/asm/dsp.h include/asm/ptrace.h include/asm/isadep.h \
  include/linux/stringify.h include/linux/spinlock_types.h \
  include/linux/lockdep.h include/linux/list.h include/linux/poison.h \
  include/linux/prefetch.h include/linux/debug_locks.h \
  include/linux/stacktrace.h include/linux/spinlock_types_up.h \
  include/linux/spinlock_up.h include/linux/spinlock_api_up.h \
  include/asm/atomic.h include/asm-generic/atomic.h include/asm/current.h \
  include/linux/timex.h include/linux/time.h include/linux/seqlock.h \
  include/asm/timex.h include/asm-mips/mach-generic/timex.h \
  include/linux/jiffies.h include/linux/calc64.h include/asm/div64.h \
  include/linux/rbtree.h include/linux/errno.h include/asm/errno.h \
  include/asm-generic/errno-base.h include/linux/nodemask.h \
  include/linux/numa.h include/asm/semaphore.h include/linux/wait.h \
  include/linux/rwsem.h include/linux/rwsem-spinlock.h include/asm/page.h \
  include/asm-generic/memory_model.h include/asm-generic/page.h \
  include/asm/mmu.h include/asm/cputime.h include/asm-generic/cputime.h \
  include/linux/smp.h include/linux/sem.h include/linux/ipc.h \
  include/asm/ipcbuf.h include/asm/sembuf.h include/linux/signal.h \
  include/asm/signal.h include/asm/sigcontext.h include/asm/siginfo.h \
  include/asm-generic/siginfo.h include/linux/securebits.h \
  include/linux/fs_struct.h include/linux/completion.h \
  include/linux/pid.h include/linux/rcupdate.h include/linux/cache.h \
  include/linux/percpu.h include/linux/slab.h include/linux/gfp.h \
  include/linux/mmzone.h include/linux/init.h \
  include/linux/memory_hotplug.h include/linux/notifier.h \
  include/linux/mutex.h include/linux/topology.h include/asm/topology.h \
  include/asm-mips/mach-generic/topology.h include/asm-generic/topology.h \
  include/linux/kmalloc_sizes.h include/asm/percpu.h \
  include/asm-generic/percpu.h include/linux/seccomp.h \
  include/linux/futex.h include/linux/rtmutex.h include/linux/plist.h \
  include/linux/param.h include/linux/resource.h include/asm/resource.h \
  include/asm-generic/resource.h include/linux/timer.h \
  include/linux/hrtimer.h include/linux/ktime.h include/linux/aio.h \
  include/linux/workqueue.h include/linux/aio_abi.h \
  include/linux/sysdev.h include/linux/kobject.h include/linux/sysfs.h \
  include/linux/kref.h include/linux/pm.h include/linux/stat.h \
  include/asm/stat.h include/linux/kmod.h include/linux/elf.h \
  include/linux/elf-em.h include/asm/elf.h include/linux/moduleparam.h \
  include/asm/local.h include/asm/module.h include/asm/uaccess.h \
  include/asm-generic/uaccess.h include/linux/pci.h \
  include/linux/pci_regs.h include/linux/pci_ids.h \
  include/linux/mod_devicetable.h include/linux/ioport.h \
  include/linux/device.h include/linux/klist.h include/linux/dmapool.h \
  include/asm/io.h include/asm/pgtable-bits.h \
  include/asm-mips/mach-generic/ioremap.h \
  include/asm-mips/mach-generic/mangle-port.h include/asm/scatterlist.h \
  include/asm/pci.h include/linux/mm.h include/linux/prio_tree.h \
  include/linux/fs.h include/linux/limits.h include/linux/ioctl.h \
  include/asm/ioctl.h include/linux/kdev_t.h include/linux/dcache.h \
  include/linux/radix-tree.h include/linux/quota.h \
  include/linux/dqblk_xfs.h include/linux/dqblk_v1.h \
  include/linux/dqblk_v2.h include/linux/nfs_fs_i.h include/linux/nfs.h \
  include/linux/sunrpc/msg_prot.h include/linux/fcntl.h \
  include/asm/fcntl.h include/asm-generic/fcntl.h include/linux/err.h \
  include/asm/pgtable.h include/asm/pgtable-64.h \
  include/asm-generic/pgtable-nopud.h include/asm-generic/pgtable.h \
  include/linux/page-flags.h include/linux/vmstat.h \
  include/linux/config.h include/linux/autoconf.h \
  include/asm-generic/pci-dma-compat.h include/linux/dma-mapping.h \
  include/asm/dma-mapping.h include/linux/highmem.h \
  include/asm/cacheflush.h include/linux/blkdev.h include/linux/major.h \
  include/linux/genhd.h include/linux/pagemap.h \
  include/linux/backing-dev.h include/linux/mempool.h include/linux/bio.h \
  include/linux/ioprio.h include/linux/elevator.h include/linux/delay.h \
  include/asm/delay.h include/asm/compiler.h include/linux/interrupt.h \
  include/linux/irqreturn.h include/linux/hardirq.h \
  include/linux/smp_lock.h include/asm/hardirq.h include/linux/irq.h \
  include/asm/irq.h include/asm/mipsmtregs.h \
  include/asm-mips/mach-generic/irq.h include/asm/hw_irq.h \
  include/linux/profile.h include/linux/irq_cpustat.h \
  include/linux/suspend.h include/linux/swap.h \
  include/linux/scatterlist.h include/scsi/scsi.h \
  drivers/scsi/scsi_priv.h include/scsi/scsi_cmnd.h \
  include/scsi/scsi_host.h include/linux/libata.h include/linux/ata.h \
  drivers/scsi/libata.h
drivers/scsi/libata-core.o:
	  mipsel-linux-gcc -Wp,-MD,drivers/scsi/.libata-core.o.d  -nostdinc -isystem /mnt/sdb2/opt/gcc-3.4.6-2f/bin/../lib/gcc/mipsel-linux/3.4.6/include -D__KERNEL__ -Iinclude  -include include/linux/autoconf.h -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -O2  -mabi=64 -G 0 -mno-abicalls -fno-pic -pipe -msoft-float -ffreestanding  -march=r4600 -Wa,--trap -Iinclude/asm-mips/mach-longmeng -Wa,-mfix-gs2f-kernel -Iinclude/asm-mips/mach-generic -fomit-frame-pointer  -Wdeclaration-after-statement      -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(libata_core)"  -D"KBUILD_MODNAME=KBUILD_STR(libata_core)" -c -o drivers/scsi/libata-core.o drivers/scsi/libata-core.c
