#define HT1_RECONNECT   1
//HT GEN1.0/3.0 cfg
#define HT1_GEN_CFG     1
//HT1 width cfg
#ifdef  LS7A_2WAY_CONNECT
#define HT1_WIDTH_CFG   HT_WIDTH_CTRL_8BIT  //only support 8 bit
#else
#define HT1_WIDTH_CFG   HT_WIDTH_CTRL_8BIT
#endif
//HT1 freq cfg
#if (HT1_GEN_CFG == 3) 
#define HT1_HARD_FREQ_CFG   HT_GEN3_FREQ_CTRL_800M
#else
#define HT1_HARD_FREQ_CFG   HT_GEN1_FREQ_CTRL_800M
#endif
#define LS7A_HT1_SOFT_FREQ_CFG   (LS7A_HT_PLL_800M | (0x1 << 1))
#define LS3A_HT1_SOFT_FREQ_CFG   (LS3A_HT_PLL_800M | (0x1 << 1))

#define LS7A_PCIE_F0_P0_DISABLE 0
#define LS7A_PCIE_F0_P1_DISABLE 0
#define LS7A_PCIE_F0_P2_DISABLE 0
#define LS7A_PCIE_F0_P3_DISABLE 0
#define LS7A_PCIE_F1_P0_DISABLE 0
#define LS7A_PCIE_F1_P1_DISABLE 1
#define LS7A_PCIE_G0_P0_DISABLE 0
#define LS7A_PCIE_G0_P1_DISABLE 1
#define LS7A_PCIE_G1_P0_DISABLE 0
#define LS7A_PCIE_G1_P1_DISABLE 1
#define LS7A_PCIE_H_P0_DISABLE  0
#define LS7A_PCIE_H_P1_DISABLE  1

#define LS7A_SATA0_DISABLE  0
#define LS7A_SATA1_DISABLE  0
#define LS7A_SATA2_DISABLE  0
#define LS7A_USB0_DISABLE   0
#define LS7A_USB1_DISABLE   0
#define LS7A_LPC_DISABLE    1

//#define USE_PCIE_PAD_REFCLK
//#define USE_SATA_PAD_REFCLK
#define USE_USB_SYS_REFCLK
