ifndef S
S:=$(shell cd ../../../..; pwd)
endif
TARGET= ${S}/Targets/Bonito3a780e
SUBTARGET?=Bonito
CPPFLAGS=-mips3 -mfp32 -fcommon

%OBJS

%CFILES

%SFILES

%LOAD

export CFILES OBJS SFILES
include ${S}/Makefile.inc

%RULES
